### ISSUE TITLE
Error when trying to install Hydrus-dd

### ISSUE THREAD

**Issue by WorldTeacher** [KichangKim/DeepDanbooru#49]
I tried installing [hydrus-dd](https://gitgud.io/koto/hydrus-dd), which uses DeepDanbooru and I got the following error:
`    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-1ddf0il_/deepdanbooru/setup.py'"'"'; __file__='"'"'/tmp/pip-install-1ddf0il_/deepdanbooru/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-1ddf0il_/deepdanbooru/pip-egg-info
         cwd: /tmp/pip-install-1ddf0il_/deepdanbooru/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-1ddf0il_/deepdanbooru/setup.py", line 12, in <module>
        version = re.search("__version__ = '([^']+)'", f.read()).group(1)  # type: ignore
    AttributeError: 'NoneType' object has no attribute 'group'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
`

**Comment by WorldTeacher** [comment]
the Issue seems to be in this line: [Image](https://cdn.discordapp.com/attachments/543452769479294986/927592244939214960/unknown.png)

**Comment by rachmadaniHaryono** [comment]
it is caused by this commit https://github.com/KichangKim/DeepDanbooru/commit/c9bbfb0ab6e6027607b3b2fc80c1ae9ca32ce7b5

especially this line
https://github.com/KichangKim/DeepDanbooru/commit/c9bbfb0ab6e6027607b3b2fc80c1ae9ca32ce7b5#diff-57ea504dee22088ee4f6f647f65bd14d050760a003882d20aaede488f52c5306R7

other than what you recommended, you can also change the regex used on setup

https://github.com/KichangKim/DeepDanbooru/blob/c9bbfb0ab6e6027607b3b2fc80c1ae9ca32ce7b5/setup.py#L12

```python
    version = re.search("__version__ = "([^"]+)'", f.read()).group(1)  # type: ignore
 ```

**Comment by KichangKim** [comment]
Black formatter makes all single quote to double quote. I fixed it (https://github.com/KichangKim/DeepDanbooru/commit/92ba0b56be5eed0037e3f067bb9867f5ac691647)
